"use strict";

define([
    'mira/widgets/render',
    'mira/base/init',
    'mira/models/api',
    'mira/models/selection',
    'mira/models/abstract',
    'mira/models/concrete',
    'mira/models/map',
    'mira/models/rule',
    'libs/responsivevoice',
    'libs/sprintf.min',
    'libs/resampler',
    //'libs/artyom.min',
    //'libs/recorderWorker',
    //'libs/recorder',
    'libs/processors',
    //'libs/vad',
    //'libs/tts',
    //'libs/WebAudioRecorder.min',
    'libs/api.ai',
    'libs/appAPI',
    'mira/application',
    'mira/interface',
    'mira/helper',

], function(
        Widget,
        Base,
        Api,
        Selection,
        Abstract,
        Concrete,
        Map,
        Rule,
        ResponsiveVoice,
        Sprintf,
        Resampler,
        //Artyom,
        //RecorderWorker,
        //Recorder,
        Processors,
        //VAD,
        //TTS,
        //WebAudioRecorder,
        APIAi,
        MiraApiai,
        Application,
        Interface,
        Helper
    ) {

    return {
        Base: Base,
        Api: Api,
        Selection: Selection,
        Rule: Rule,
        Concrete: Concrete,
        Abstract: Abstract,
        Map : Map,
        Widget : Widget,
        ResponsiveVoice: ResponsiveVoice,
        Sprintf: Sprintf,
        //Artyom: Artyom,
        //Resampler: Resampler,
        //RecorderWorker : RecorderWorker,
        //Recorder : Recorder,
        Processors : Processors,
        //VAD : VAD,
        //TTS : TTS,
        //WebAudioRecorder: WebAudioRecorder,
        APIAi : APIAi,
        MiraApiai : MiraApiai,
        Application : Application,
        Interface: Interface,
        Helper: Helper
    }
});