"use strict";

define([
    'mira/widgets/render',
    'mira/base/init',
    'mira/models/api',
    'mira/models/selection',
    'mira/models/abstract',
    'mira/models/concrete',
    'mira/models/map',
    'mira/models/rule',
    'jlibs/bootstrap-accessibility.min',
    'libs/sprintf.min',
    'libs/resampler',
    'libs/processors',
    'libs/rs.speech',
    //'libs/hark',
    'libs/api.ai',
    'libs/appAPI',
    'libs/recorder',
    'libs/jquery.easing.min',
    'libs/agency.min',
    'mira/application',
    'mira/interface',
    'mira/helper',

], function(
        Widget,
        Base,
        Api,
        Selection,
        Abstract,
        Concrete,
        Map,
        Rule,
        PayPalPlugin,
        Sprintf,
        Resampler,
        Processors,
        Speech,
    //    Hark,
        APIAi,
        MiraApiai,
        Recorder,
        JqueryEasing,
        Agency,
        Application,
        Interface,
        Helper
    ) {

    return {
        Base: Base,
        Api: Api,
        Selection: Selection,
        Rule: Rule,
        Concrete: Concrete,
        Abstract: Abstract,
        Map : Map,
        Widget : Widget,
        PayPalPlugin: PayPalPlugin,
        Sprintf: Sprintf,
        Processors : Processors,
        Speech: Speech,
    //    Hark: Hark,
        APIAi : APIAi,
        MiraApiai : MiraApiai,
        Recorder: Recorder,
        JqueryEasing: JqueryEasing,
        Agency: Agency,
        Application : Application,
        Interface: Interface,
        Helper: Helper
    }
});